<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~A</string>
	<key>name</key>
	<string>MASM Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^\s*(include)\b\s+</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.asm.masm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.preprocessor.asm.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.asm</string>
						</dict>
					</dict>
					<key>end</key>
					<string>"</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.asm</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.include.asm</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^(\.data)$</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.segment</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)^(\.code)$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)^\s*([a-z_]\w*)\s+([a-z]+)\s+</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.other</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>storage.type</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#literals</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^([a-z_]\w*)\s+(proc)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(\1)\s+(endp)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\b(uses)\b</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#registers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#bodyCode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)^([a-z_]\w*)\s+(macro)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.macro</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?i)(endm)$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.other</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?i)(?&lt;=macro)</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#variableName</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#bodyCode</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bodyCode</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#instructionLine</string>
				</dict>
			</array>
		</dict>
		<key>callSyntax</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.opcode</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>meta.function</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\b(call)\s+([a-z_]\w*)\b</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line.character</string>
		</dict>
		<key>controlOpcodes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.label</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i)\b(jz|jnz|jc|jnc|jmp|jne|je)\s+([a-z_]\w*)</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b(ret|exit)</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>indirectionBrackets</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>contentName</key>
			<string>variable.other</string>
			<key>end</key>
			<string>\]</string>
			<key>name</key>
			<string>meta.embedded.line</string>
		</dict>
		<key>instructionLine</key>
		<dict>
			<key>begin</key>
			<string>^</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#label</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#offsetModifier</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#indirectionBrackets</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#controlOpcodes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#callSyntax</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#opcodes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#registers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#literals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#variableName</string>
				</dict>
			</array>
		</dict>
		<key>label</key>
		<dict>
			<key>match</key>
			<string>^\S+:</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.dec</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b[01]+b\b</string>
					<key>name</key>
					<string>constant.numeric.binary</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i)\b[0-9a-f]+h\b</string>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
			</array>
		</dict>
		<key>offsetModifier</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(offset)\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<key>opcodes</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(mov|movzx|add|and|or|xor|not|cmp|test|inc|dec|shr|shl|ror|rol)\b</string>
			<key>name</key>
			<string>keyword.operator.opcode</string>
		</dict>
		<key>registers</key>
		<dict>
			<key>match</key>
			<string>(?i)\b(ip|eip|eax|ebx|ecx|edx|edi|esi|ebp|esp|ax|bx|cx|dx|di|si|bp|sp|ah|al|bh|bl|ch|cl|dh|dl|ax|bx|cx|dx|cs|ds|ss|es|fs|gs|cr0|cr2|cr3|db0|db1|db2|db3|db6|db7|tr6|tr7|st)\b</string>
			<key>name</key>
			<string>storage.type.register</string>
		</dict>
		<key>variableName</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b([a-z]\w*)\b</string>
		</dict>
	</dict>
	<key>scope</key>
	<string>source.asm.masm</string>
	<key>scopeName</key>
	<string>source.asm.masm</string>
	<key>uuid</key>
	<string>2D9AFA15-4843-4E38-9062-A1ABD7E344CA</string>
</dict>
</plist>
